version: '2.1'
services:


  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    ports:
      - "33600:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data_master

    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'mysql', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 45s
      interval: 10s
      retries: 10

  producer1:
    build: ./
    restart: always
    container_name: python_producers
    